services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    ports:
      - 3000:3000
      - 8000:8000
      - 5173:5173
    env_file:
      - .env
    command: sleep infinity
  db_mongodb:
    image: mongo:8
    restart: always
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0  
